function generateArtifacts(scan) {
  return {
    'AGENT_HANDOFF.md': renderAgentHandoff(scan),
    'AGENTS.md': renderAgents(scan),
    'llms.txt': renderLlmsTxt(scan),
    'handoff-pack.md': renderHandoffPack(scan)
  };
}

function renderAgentHandoff(scan) {
  const lines = [
    `# ${scan.projectName} Agent Handoff`,
    '',
    'This file was generated by `agent-handoff-kit` to help the next AI coding agent become useful quickly.',
    '',
    '## Project Snapshot',
    '',
    `- Repository: \`${scan.projectName}\``,
    `- Stack: ${formatList(scan.stack)}`,
    `- Package manager: ${scan.packageManager ? `\`${scan.packageManager}\`` : 'not detected'}`,
    `- Git branch: ${scan.git ? `\`${scan.git.branch}\`` : 'not detected'}`,
    `- Working tree: ${scan.git ? (scan.git.dirty ? 'has local changes' : 'clean') : 'not detected'}`,
    '',
    '## Common Commands',
    '',
    ...renderCommands(scan),
    '',
    '## Important Files',
    '',
    ...renderBullets(scan.files.slice(0, 25).map((file) => `\`${file.path}\` (${formatBytes(file.size)})`)),
    '',
    '## Documentation',
    '',
    ...renderBullets(scan.docs.map((file) => `\`${file}\``)),
    '',
    '## Configuration',
    '',
    ...renderBullets(scan.configs.map((file) => `\`${file}\``)),
    '',
    '## Current Git Changes',
    '',
    ...renderGitChanges(scan),
    '',
    '## Instructions For The Next Agent',
    '',
    '- Read this file before making edits.',
    '- Inspect the working tree before changing files.',
    '- Do not overwrite user changes.',
    '- Prefer existing project scripts and conventions.',
    '- Run the most relevant verification command before claiming completion.',
    ''
  ];

  return lines.join('\n');
}

function renderAgents(scan) {
  const testCommand = commandForScript(scan, 'test');
  const buildCommand = commandForScript(scan, 'build');
  const lines = [
    `# AGENTS.md`,
    '',
    `Guidance for AI coding agents working in ${scan.projectName}.`,
    '',
    '## Operating Rules',
    '',
    '- Inspect the repository before editing.',
    '- Keep changes focused on the requested task.',
    '- Do not overwrite user changes.',
    '- Prefer small, reviewable commits when committing is requested.',
    '- Use existing scripts, style, and project conventions.',
    '',
    '## Verification',
    '',
    testCommand ? `- Test: \`${testCommand}\`` : '- Test command: not detected.',
    buildCommand ? `- Build: \`${buildCommand}\`` : '- Build command: not detected.',
    '',
    '## Project Handoff',
    '',
    '- Read `AGENT_HANDOFF.md` for the current repository snapshot.',
    '- Use `handoff-pack.md` when opening a fresh agent session.',
    ''
  ];

  return lines.join('\n');
}

function renderLlmsTxt(scan) {
  const lines = [
    `# ${scan.projectName}`,
    '',
    `> AI coding agent context generated by agent-handoff-kit.`,
    '',
    '## Summary',
    '',
    `${scan.projectName} is a ${formatList(scan.stack).toLowerCase()} project.`,
    '',
    '## Useful Entry Points',
    '',
    '- `AGENT_HANDOFF.md`: repository snapshot for coding agents.',
    '- `AGENTS.md`: operating rules for AI coding agents.',
    '- `handoff-pack.md`: copy-paste context bundle for a new chat.',
    ...scan.docs.map((file) => `- \`${file}\`: project documentation.`),
    '',
    '## Commands',
    '',
    ...renderCommands(scan),
    ''
  ];

  return lines.join('\n');
}

function renderHandoffPack(scan) {
  const lines = [
    `# ${scan.projectName} Handoff Pack`,
    '',
    'Paste this into a fresh AI coding agent session:',
    '',
    '```text',
    `You are working in the ${scan.projectName} repository.`,
    `Stack: ${formatList(scan.stack)}.`,
    `Package manager: ${scan.packageManager || 'not detected'}.`,
    scan.git ? `Current branch: ${scan.git.branch}. Working tree: ${scan.git.dirty ? 'has local changes' : 'clean'}.` : 'Git status was not detected.',
    '',
    'Before editing:',
    '1. Read AGENT_HANDOFF.md and AGENTS.md.',
    '2. Inspect git status and existing project scripts.',
    '3. Preserve user changes and follow local conventions.',
    '',
    'Useful commands:',
    ...renderCommands(scan).map((line) => line.replace(/^- /, '')),
    '',
    'Important files:',
    ...scan.files.slice(0, 20).map((file) => `- ${file.path}`),
    '```',
    ''
  ];

  return lines.join('\n');
}

function renderCommands(scan) {
  const scripts = scan.scripts || {};
  const names = Object.keys(scripts);
  if (names.length === 0) {
    return ['- No package scripts detected.'];
  }

  return names.map((name) => `- \`${commandForScript(scan, name)}\` - ${scripts[name]}`);
}

function commandForScript(scan, name) {
  if (!scan.scripts || !scan.scripts[name]) {
    return null;
  }
  const runner = scan.packageManager || 'npm';
  if (runner === 'yarn') return `yarn ${name}`;
  if (runner === 'pnpm') return `pnpm ${name}`;
  if (runner === 'bun') return `bun run ${name}`;
  if (['test', 'start', 'restart', 'stop'].includes(name)) return `npm ${name}`;
  return `npm run ${name}`;
}

function renderBullets(items) {
  if (!items || items.length === 0) {
    return ['- Not detected.'];
  }
  return items.map((item) => `- ${item}`);
}

function renderGitChanges(scan) {
  if (!scan.git) {
    return ['- Git status not available.'];
  }
  if (!scan.git.dirty) {
    return ['- Working tree is clean.'];
  }
  return renderBullets(scan.git.changedFiles.map((file) => `\`${file}\``));
}

function formatList(items) {
  if (!items || items.length === 0) {
    return 'not detected';
  }
  return items.join(', ');
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  return `${Math.round(bytes / 1024)} KB`;
}

module.exports = {
  generateArtifacts
};
